<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-13 04:11
=======
# Generated by Django 4.2.6 on 2023-10-10 02:51
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("UserId", models.IntegerField(primary_key=True, serialize=False)),
>>>>>>> main
            ],
        ),
    ]
